/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary-fixed-variant": "#802a00",
        "surface-container-low": "#f0f3ff",
        "tertiary-container": "#872d00",
        "tertiary-fixed-dim": "#ffb59a",
        "on-primary": "#ffffff",
        "inverse-primary": "#b8c4ff",
        "surface-container-highest": "#dce2f3",
        "tertiary-fixed": "#ffdbce",
        "inverse-on-surface": "#ebf1ff",
        "tertiary": "#611e00",
        "surface-dim": "#d3daea",
        "on-surface": "#151c27",
        surface: "#f9f9ff",
        "on-secondary-container": "#00714d",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001453",
        "surface-container-high": "#e2e8f8",
        "on-background": "#151c27",
        "surface-container": "#e7eefe",
        "secondary-container": "#6cf8bb",
        "on-tertiary-container": "#ffa583",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#93000a",
        background: "#f9f9ff",
        "inverse-surface": "#2a313d",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#173bab",
        "surface-tint": "#3755c3",
        outline: "#757684",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444653",
        "on-tertiary-fixed": "#380d00",
        "surface-variant": "#dce2f3",
        primary: "#00288e",
        "surface-bright": "#f9f9ff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c4c5d5",
        secondary: "#006c49",
        "primary-container": "#1e40af",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#a8b8ff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        xl: "32px",
        md: "16px",
        sm: "8px",
        gutter: "24px",
        base: "4px",
        xs: "4px",
        margin: "32px",
      },
      fontSize: {
        "display-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "700" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem" }],
        "body-md": ["1rem", { lineHeight: "1.5rem" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
